name: Prepare CI environment
description: Prepare CI environment
inputs:
  docker_password:
    description: Docker registry password
    required: true
runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: /bin/bash
      run: |
        echo "Hello from composite action!"
        apt update
        # ✦ cachix/install-nix-action
        apt install --yes curl sudo xz-utils
        # ✦ actions/checkout
        apt install --yes git nodejs
        # ✦ docker/setup-buildx-action
        # ✦ docker/build-push-action
        apt-get install --yes ca-certificates curl gnupg
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update
        apt-get install --yes docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Clone Nuttyverse
      uses: actions/checkout@v4
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: code.nuttyver.se
        username: nuttyversal
        password: ${{ inputs.docker_password }}
