name: Nuttyverse CI
on:
  push:
    branches:
      - main
jobs:
  blocks-µ-service:
    runs-on: [self-hosted, nix]
    container:
      image: ubuntu:mantic
    env:
      FONT_AWESOME_NPM_TOKEN: ${{ secrets.FONT_AWESOME_NPM_TOKEN }}
    steps:
      - name: Install dependencies
        run: apt update && apt install --yes git nodejs
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup path filter
        id: path-filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'blocks/**'
      - name: Prepare environment
        if: steps.path-filter.outputs.src == 'true'
        uses: ./.gitea/actions/prepare
        with:
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        if: steps.path-filter.outputs.src == 'true'
        run: |
          cd blocks
          nix-shell --run "just install"
          nix-shell --run "just test"
          nix-shell --run "just build"
      - name: Deploy
        if: steps.path-filter.outputs.src == 'true' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: blocks
          push: true
          tags: code.nuttyver.se/observable/blocks:latest
        build-args: |
          FONT_AWESOME_NPM_TOKEN=${{ secrets.FONT_AWESOME_NPM_TOKEN }}
  bot-µ-service:
    runs-on: [self-hosted, nix]
    container:
      image: ubuntu:mantic
    steps:
      - name: Install dependencies
        run: apt update && apt install --yes git nodejs
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup path filter
        id: path-filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'bot/**'
      - name: Prepare environment
        if: steps.path-filter.outputs.src == 'true'
        uses: ./.gitea/actions/prepare
        with:
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Test
        if: steps.path-filter.outputs.src == 'true'
        run: |
          cd bot
          nix-shell --run "just install"
          nix-shell --run "just test"
      - name: Deploy
        if: steps.path-filter.outputs.src == 'true' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: bot
          push: true
          tags: code.nuttyver.se/observable/bot:latest
  fonts-µ-service:
    runs-on: [self-hosted, nix]
    container:
      image: ubuntu:mantic
    steps:
      - name: Install dependencies
        run: apt update && apt install --yes git nodejs
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup path filter
        id: path-filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'fonts/**'
      - name: Prepare environment
        if: steps.path-filter.outputs.src == 'true'
        uses: ./.gitea/actions/prepare
        with:
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Test and build
        if: steps.path-filter.outputs.src == 'true'
        run: |
          cd fonts
          nix-shell --run "just test"
          nix-shell --run "just build"
      - name: Deploy
        if: steps.path-filter.outputs.src == 'true' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: fonts
          push: true
          tags: code.nuttyver.se/observable/font-force-field:latest
  city-µ-service:
    runs-on: [self-hosted, nix]
    container:
      image: ubuntu:mantic
    steps:
      - name: Install dependencies
        run: apt update && apt install --yes git nodejs
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup path filter
        id: path-filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'blocks/**'
              - 'city/**'
      - name: Prepare environment
        if: steps.path-filter.outputs.src == 'true'
        uses: ./.gitea/actions/prepare
        with:
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        if: steps.path-filter.outputs.src == 'true'
        run: |
          cd city
          nix-shell --run "just install"
          nix-shell --run "just test"
          nix-shell --run "just build"
      - name: Deploy
        if: steps.path-filter.outputs.src == 'true'
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_TOKEN }}
          dist_dir: city/dist
          cleanup: false
