name: Nuttyverse CI
on:
  push:
    branches:
      - main
env:
  FONT_AWESOME_NPM_TOKEN: ${{ secrets.FONT_AWESOME_NPM_TOKEN }}
jobs:
  blocks-µ-service:
    runs-on: [self-hosted, nix]
    container:
      image: ubuntu:mantic
    steps:
      - name: Install dependencies
        run: apt update && apt install --yes git nodejs
      - name: Setup SSH private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.UNOBSERVABLE_DEPLOY_KEY }}
      - name: Setup SSH known hosts
        run: ssh-keyscan -t ed25519 code.nuttyver.se >> ~/.ssh/known_hosts
      - name: Checkout observable repository
        uses: actions/checkout@v4
      - name: Checkout unobservable submodule
        run: git submodule update --init --recursive
      - name: Prepare environment
        uses: ./.gitea/actions/prepare
        with:
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: |
          cd blocks
          nix develop -c bash -c "just install"
          nix develop -c bash -c "just test"
          nix develop -c bash -c "just build"
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: blocks/Dockerfile
          push: true
          tags: code.nuttyver.se/observable/blocks:latest
          secrets: |
            "FONT_AWESOME_NPM_TOKEN=${{ secrets.FONT_AWESOME_NPM_TOKEN }}"
  bot-µ-service:
    runs-on: [self-hosted, nix]
    container:
      image: ubuntu:mantic
    steps:
      - name: Install dependencies
        run: apt update && apt install --yes git nodejs
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare environment
        uses: ./.gitea/actions/prepare
        with:
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Test
        run: |
          cd bot
          nix develop -c bash -c "just install"
          nix develop -c bash -c "just test"
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: bot/Dockerfile
          push: true
          tags: code.nuttyver.se/observable/bot:latest
          secrets: |
            "FONT_AWESOME_NPM_TOKEN=${{ secrets.FONT_AWESOME_NPM_TOKEN }}"
  fonts-µ-service:
    runs-on: [self-hosted, nix]
    container:
      image: ubuntu:mantic
    steps:
      - name: Install dependencies
        run: apt update && apt install --yes git nodejs
      - name: Setup SSH private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.UNOBSERVABLE_DEPLOY_KEY }}
      - name: Setup SSH known hosts
        run: ssh-keyscan -t ed25519 code.nuttyver.se >> ~/.ssh/known_hosts
      - name: Checkout observable repository
        uses: actions/checkout@v4
      - name: Checkout unobservable submodule
        run: git submodule update --init --recursive
      - name: Prepare environment
        uses: ./.gitea/actions/prepare
        with:
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Test and build
        run: |
          cd fonts
          nix develop -c bash -c "just test"
          nix develop -c bash -c "just build"
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: fonts/Dockerfile
          push: true
          tags: code.nuttyver.se/observable/font-force-field:latest
  city-µ-service:
    runs-on: [self-hosted, nix]
    container:
      image: ubuntu:mantic
    steps:
      - name: Install dependencies
        run: apt update && apt install --yes git nodejs
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare environment
        uses: ./.gitea/actions/prepare
        with:
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: |
          cd city
          nix develop -c bash -c "just install"
          nix develop -c bash -c "just test"
          nix develop -c bash -c "just build"
      - name: Deploy
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_TOKEN }}
          dist_dir: city/dist
          cleanup: false
