name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on:
  push:
    branches:
      - main
jobs:
  explore-gitea-actions:
    runs-on: [self-hosted, nix]
    container:
      image: ubuntu:noble
    steps:
      - name: Install dependencies
        run: |
          apt update
          # ✦ cachix/install-nix-action
          apt install --yes sudo
          # ✦ actions/checkout
          apt install --yes git nodejs
      - name: Install Nix package manager
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Clone the Nuttyverse
        uses: actions/checkout@v4
      - name: Validate Nix installation
        run: nix --version
