name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: [self-hosted, nix]
    container:
      image: ubuntu:mantic
    steps:
      - name: Install dependencies
        run: |
          apt update
          # ✦ cachix/install-nix-action
          apt install --yes curl sudo xz-utils
          # ✦ actions/checkout
          apt install --yes git nodejs
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Clone Nuttyverse
        uses: actions/checkout@v4
      - name: Build design system
        run: |
          cd blocks
          nix-shell --run "pnpm install"
          nix-shell --run "pnpm run build-storybook"
      - name: Build font server
        run: |
          cd fonts
          nix-shell --run "cargo test"
          nix-shell --run "cargo build"
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted, nix]
    container:
      image: ubuntu:mantic
    steps:
      - name: Install dependencies
        run: |
          apt update
          # ✦ actions/checkout
          apt install --yes git nodejs
          # ✦ docker/setup-buildx-action
          # ✦ docker/build-push-action
          apt-get install --yes ca-certificates curl gnupg
          install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          chmod a+r /etc/apt/keyrings/docker.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            tee /etc/apt/sources.list.d/docker.list > /dev/null
          apt-get update
          apt-get install --yes docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      - name: Clone Nuttyverse
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: code.nuttyver.se
          username: nuttyversal
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy design system
        uses: docker/build-push-action@v5
        with:
          context: blocks
          push: true
          tags: code.nuttyver.se/observable/blocks:latest
      - name: Deploy font server
        uses: docker/build-push-action@v5
        with:
          context: fonts
          push: true
          tags: code.nuttyver.se/observable/font-force-field:latest
